try:
    from config_local import (
        CLICK_DELAY,
        DEADSPACE_X,
        DEADSPACE_Y,
        DUPLICATE_TOLERANCE,
        IMAGE_TOLERANCE,
        SCROLL_DELAY,
        SCROLL_PIXELS,
        SEARCH_BAR_X,
        SEARCH_BAR_Y,
        TWITTER_USERNAME,
    )
except ImportError:
    from config import (
        CLICK_DELAY,
        DEADSPACE_X,
        DEADSPACE_Y,
        DUPLICATE_TOLERANCE,
        IMAGE_TOLERANCE,
        SCROLL_DELAY,
        SCROLL_PIXELS,
        SEARCH_BAR_X,
        SEARCH_BAR_Y,
        TWITTER_USERNAME,
    )

SEARCH_BAR_COORD = [SEARCH_BAR_X, SEARCH_BAR_Y]
REFRESH_BUTTON_COORD = [118, 78]
BASE_UNFOLLOW_URL = f"https://x.com/{TWITTER_USERNAME}/following"
IMAGE_REC_TOLERANCE = IMAGE_TOLERANCE
SCROLL_PAUSE_TIME = SCROLL_DELAY
DEADSPACE = [DEADSPACE_X, DEADSPACE_Y]
DUPE_COORD_TOL = DUPLICATE_TOLERANCE
UNFOLLOW_CLICK_TIMEOUT = CLICK_DELAY
SCROLL_AMOUNT = SCROLL_PIXELS